### ISSUE TITLE
Unknown command line flag 'f'

### ISSUE THREAD

**Issue by ghost** [mdeff/cnn_graph#45] opened 2019-09-19 21:54 UTC
```
UnrecognizedFlagError                     Traceback (most recent call last)
<ipython-input-3-0b079301697c> in <module>
      1 # Fetch dataset. Scikit-learn already performs some cleaning.
      2 remove = ('headers','footers','quotes')  # (), ('headers') or ('headers','footers','quotes')
----> 3 train = utils.Text20News(data_home=FLAGS.dir_data, subset='train', remove=remove)
      4 
      5 # Pre-processing: transform everything to a-z and whitespace.

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/platform/flags.py in __getattr__(self, name)
     82     # a flag.
     83     if not wrapped.is_parsed():
---> 84       wrapped(_sys.argv)
     85     return wrapped.__getattr__(name)
     86 

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/absl/flags/_flagvalues.py in __call__(self, argv, known_only)
    631       suggestions = _helpers.get_flag_suggestions(name, list(self))
    632       raise _exceptions.UnrecognizedFlagError(
--> 633           name, value, suggestions=suggestions)
    634 
    635     self.mark_as_parsed()

UnrecognizedFlagError: Unknown command line flag 'f'
UnrecognizedFlagError: Unknown command line flag 'f'

make: *** [20news.ipynb] Error 1
```

**Comment by ghost** [comment] 2019-09-19 21:55
I installed the Ternsorflow and used "make" to run examples

**Comment by BingYu94860** [comment] 2019-09-28 16:04
tf.app.flags.DEFINE_string('f', '', 'kernel')#添加的，不报错

https://blog.csdn.net/qq_33266320/article/details/83548869

**Comment by mdeff** [comment] 2020-07-20 17:26
Can you try with `tensorflow-gpu==1.1.0` ([that's the version I used to develop the code](https://github.com/mdeff/cnn_graph/commit/f7f7ba1e0094642fce4353dbe53d8809c98ada22)).

**Comment by mdeff** [comment] 2020-07-20 17:51
Duplicate of #27.

**Closed as completed by mdeff** 2020-07-20 17:51 UTC

**Comment by happysheep224** [comment] 2020-08-07 09:35
```
UnrecognizedFlagError                     Traceback (most recent call last)
<ipython-input-3-0b079301697c> in <module>
      1 # Fetch dataset. Scikit-learn already performs some cleaning.
      2 remove = ('headers','footers','quotes')  # (), ('headers') or ('headers','footers','quotes')
----> 3 train = utils.Text20News(data_home=FLAGS.dir_data, subset='train', remove=remove)
      4 
      5 # Pre-processing: transform everything to a-z and whitespace.

~/opt/anaconda3/envs/gnn/lib/python3.7/site-packages/tensorflow_core/python/platform/flags.py in __getattr__(self, name)
     82     # a flag.
     83     if not wrapped.is_parsed():
---> 84       wrapped(_sys.argv)
     85     return wrapped.__getattr__(name)
     86 

~/opt/anaconda3/envs/gnn/lib/python3.7/site-packages/absl/flags/_flagvalues.py in __call__(self, argv, known_only)
    631       suggestions = _helpers.get_flag_suggestions(name, list(self))
    632       raise _exceptions.UnrecognizedFlagError(
--> 633           name, value, suggestions=suggestions)
    634 
    635     self.mark_as_parsed()

UnrecognizedFlagError: Unknown command line flag 'HistoryManager.hist_file'
UnrecognizedFlagError: Unknown command line flag 'HistoryManager.hist_file'
```

**Comment by happysheep224** [comment] 2020-08-07 09:35
what's wrong with it ?

**Comment by mdeff** [comment] 2020-08-13 14:51
Please try with `tensorflow-gpu==1.1.0` or the solution posted at https://github.com/mdeff/cnn_graph/issues/27#issuecomment-416582356.
